
install.packages("RcppArmadillo") # not from source
# R will ask you if you want to install this from source - please type N
lapply(c("tidyverse",
                 "fivethirtyeight",
                 "gapminder",
                 "ggrepel",
                 "gganimate",
                 "ggridges",
                 "ggthemes",
                 "coefplot",
                 "jsonlite",
                 "statnet",
                 "igraph",
                 "tm",
                 "tidytext",
                 "readtext",
                 "rvest",
                 "stringr",
                 "devtools",
                 "wordcloud",
                 "proxy",
                 "fpc",
                 "cluster",
                 "janeaustenr",
                 "gutenbergr",
                 "ggraph",
                 "syuzhet",
                 "plotly",
                 "caret",
                 "ggplot2",
                 "mlbench",
                 "class",
                 "caTools",
                 "randomForest",
                 "ranger",
                 "kernlab",
                 "class",
                 "glmnet",
                 "naivebayes",
                 "rpart",
                 "rpart.plot"),library, character.only=TRUE)

